[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.build]
cmds = [
  "cd client && npm install && npm run build",
  "cd server && npm install && npx prisma generate && npx prisma db push && npm run build"
]

[start]
cmd = "cd server && node dist/index.js"
